# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI-GO-Build&Test

on:
  push: # Run if pushed to a branch but ingore if its a update to a .folder
    paths-ignore:
      - ".terraform/**"
      - ".docker/**"
      - ".devcontainer/**"
      - ".github/**"
      - ".gitignore"
      - "README.md"
  pull_request: # Run if pull request to a branch but ingore if its a update to a .folder
    paths-ignore:
      - ".terraform/**"
      - ".docker/**"
      - ".devcontainer/**"
      - ".github/**"
      - ".gitignore"
      - "README.md"


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.3'

    - name: Build
      run: go build -v ./...

