name: 'Dependency Review'
on:
  pull_request:
    paths-ignore: 
      - ".devcontainer/**"
      - ".github/**"
      - ".gitignore"
      - "README.md"
  push:
    paths-ignore: 
      - ".devcontainer/**"
      - ".github/**"
      - ".gitignore"
      - "README.md"


permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: 'arc-runner-set'
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
